Polynomial Arithmetic: src/demo.cpp File Reference
demo.cpp File Reference
#include "../include/Polynomial.hpp"
#include <iostream>
#include <string>
#include <stdexcept>
Functions
void print_help ()
This file demonstrates the top-level funtionalities of the Polynomial class.
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 27 of file demo.cpp.
References Polynomial< FieldT >::appendTerm(), and print_help().
void print_help ()
This file demonstrates the top-level funtionalities of the Polynomial class.
Definition at line 22 of file demo.cpp.
Referenced by main().