Polymetic: anonymous_namespace{MatrixAlgorithms_impl.ipp} Namespace Reference
anonymous_namespace{MatrixAlgorithms_impl.ipp} Namespace Reference
Functions
template<typename MatrixT >
MatrixT exp_by_squaring (const MatrixT &M, size_t n)
template<typename MatrixT >
MatrixT::value_type trace (const MatrixT &M, size_t n)
Function Documentation
template<typename MatrixT > MatrixT anonymous_namespace{MatrixAlgorithms_impl.ipp}::exp_by_squaring (const MatrixT & M, size_t n)
Definition at line 28 of file MatrixAlgorithms_impl.ipp.
References boost::numeric::ublas::isSquare().
Referenced by exp().
template<typename MatrixT > MatrixT::value_type anonymous_namespace{MatrixAlgorithms_impl.ipp}::trace (const MatrixT & M, size_t n)
< expecting two move operations. First
Todo:
remove direct reference to iterator1. Make is general.
Definition at line 53 of file MatrixAlgorithms_impl.ipp.
References exp(), and boost::numeric::ublas::isSquare().
Referenced by det().