Polymetic: boost::numeric::ublas Namespace Reference
boost::numeric::ublas Namespace Reference
Functions
template<typename EntryT >
EntryT trace (const Matrix< EntryT > &M)
Finds trace of a square matrix.
template<typename MatrixT >
bool isSquare (const MatrixT &M)
Convinience function to check if a matrix is square or not.
Function Documentation
template<typename MatrixT > bool boost::numeric::ublas::isSquare (const MatrixT & M)
Convinience function to check if a matrix is square or not.
Definition at line 44 of file Matrix_impl.ipp.
Referenced by det(), anonymous_namespace{MatrixAlgorithms_impl.ipp}::exp_by_squaring(), and anonymous_namespace{MatrixAlgorithms_impl.ipp}::trace().
template<typename EntryT > EntryT boost::numeric::ublas::trace (const Matrix< EntryT > & M)
Finds trace of a square matrix.
Detailed description of the function {strong}{Throws std::invalid_argument if the supplied matrix is now square}
Returns
trace Trace of a square matrix
Definition at line 25 of file Matrix_impl.ipp.
Referenced by anonymous_namespace{Test_MatrixAlgorithms_double.cpp}::TEST_F(), anonymous_namespace{Test_MatrixAlgorithms_polynomial_double.cpp}::TEST_F(), and anonymous_namespace{Test_Matrix_Operations.cpp}::TEST_F().