Polymetic: anonymous_namespace{Test_MatrixAlgorithms_polynomial_double.cpp} Namespace Reference
anonymous_namespace{Test_MatrixAlgorithms_polynomial_double.cpp} Namespace Reference
Classes
class MatrixTest
Functions
TEST_F (MatrixTest, trace_with_power)
TEST_F (MatrixTest, determinant)
TEST_F (MatrixTest, determinant_large_5_5)
TEST_F (MatrixTest, determinant_large_5_10)
TEST_F (MatrixTest, determinant_large_10_10)
Function Documentation
anonymous_namespace{Test_MatrixAlgorithms_polynomial_double.cpp}::TEST_F (MatrixTest , trace_with_power)
Definition at line 51 of file Test_MatrixAlgorithms_polynomial_double.cpp.
References boost::numeric::ublas::trace().
anonymous_namespace{Test_MatrixAlgorithms_polynomial_double.cpp}::TEST_F (MatrixTest , determinant)
Definition at line 109 of file Test_MatrixAlgorithms_polynomial_double.cpp.
References det().
anonymous_namespace{Test_MatrixAlgorithms_polynomial_double.cpp}::TEST_F (MatrixTest , determinant_large_5_5)
Definition at line 163 of file Test_MatrixAlgorithms_polynomial_double.cpp.
References det().
anonymous_namespace{Test_MatrixAlgorithms_polynomial_double.cpp}::TEST_F (MatrixTest , determinant_large_5_10)
Definition at line 180 of file Test_MatrixAlgorithms_polynomial_double.cpp.
References det().
anonymous_namespace{Test_MatrixAlgorithms_polynomial_double.cpp}::TEST_F (MatrixTest , determinant_large_10_10)
Definition at line 197 of file Test_MatrixAlgorithms_polynomial_double.cpp.
References det().