Polymetic: test/Test_Polynomial.cpp File Reference
Test_Polynomial.cpp File Reference
Contains the tests for the class Polynomial with field type as "double".
#include "../include/Polynomial.ipp"
#include "gtest/gtest.h"
#include <stdexcept>
#include <utility>
#include <vector>
Classes
class PolynomialTest
Functions
TEST_F (PolynomialTest, constructor_default)
TEST_F (PolynomialTest, constructor_init_list)
TEST_F (PolynomialTest, constructor_iterators)
TEST_F (PolynomialTest, appendTerm)
TEST_F (PolynomialTest, constructor_copy)
TEST_F (PolynomialTest, constructor_move)
TEST_F (PolynomialTest, assignment_move)
TEST_F (PolynomialTest, access_operator_out_of_range_exception)
TEST_F (PolynomialTest, friend_swap)
TEST_F (PolynomialTest, helper_trim)
TEST_F (PolynomialTest, sum_assign_operator)
TEST_F (PolynomialTest, sum_assign_operator_rvalue_ref)
TEST_F (PolynomialTest, subtract_assign_operator)
TEST_F (PolynomialTest, subtract_assign_operator_rvalue_ref)
TEST_F (PolynomialTest, unary_minus_operator_rvalue)
TEST_F (PolynomialTest, unary_minus_operator)
TEST_F (PolynomialTest, helper_minus)
TEST_F (PolynomialTest, add_operator)
TEST_F (PolynomialTest, add_operator_rvalue)
TEST_F (PolynomialTest, subtract_operator)
TEST_F (PolynomialTest, multiply_operator)
int main (int argc, char **argv)
Detailed Description
Contains the tests for the class Polynomial with field type as "double".
Definition in file Test_Polynomial.cpp.
Function Documentation
int main (int argc, char ** argv)
Definition at line 349 of file Test_Polynomial.cpp.
TEST_F (PolynomialTest , constructor_default)
Definition at line 47 of file Test_Polynomial.cpp.
References Polynomial< FieldT >::size().
TEST_F (PolynomialTest , constructor_init_list)
Definition at line 51 of file Test_Polynomial.cpp.
TEST_F (PolynomialTest , constructor_iterators)
Definition at line 59 of file Test_Polynomial.cpp.
TEST_F (PolynomialTest , appendTerm)
Definition at line 67 of file Test_Polynomial.cpp.
References Polynomial< FieldT >::appendTerm().
TEST_F (PolynomialTest , constructor_copy)
Definition at line 78 of file Test_Polynomial.cpp.
TEST_F (PolynomialTest , constructor_move)
Definition at line 87 of file Test_Polynomial.cpp.
TEST_F (PolynomialTest , assignment_move)
Definition at line 97 of file Test_Polynomial.cpp.
TEST_F (PolynomialTest , access_operator_out_of_range_exception)
Definition at line 108 of file Test_Polynomial.cpp.
TEST_F (PolynomialTest , friend_swap)
Definition at line 114 of file Test_Polynomial.cpp.
TEST_F (PolynomialTest , helper_trim)
Definition at line 129 of file Test_Polynomial.cpp.
TEST_F (PolynomialTest , sum_assign_operator)
Definition at line 145 of file Test_Polynomial.cpp.
TEST_F (PolynomialTest , sum_assign_operator_rvalue_ref)
Definition at line 166 of file Test_Polynomial.cpp.
TEST_F (PolynomialTest , subtract_assign_operator)
Definition at line 180 of file Test_Polynomial.cpp.
TEST_F (PolynomialTest , subtract_assign_operator_rvalue_ref)
Definition at line 201 of file Test_Polynomial.cpp.
TEST_F (PolynomialTest , unary_minus_operator_rvalue)
Definition at line 215 of file Test_Polynomial.cpp.
TEST_F (PolynomialTest , unary_minus_operator)
Definition at line 224 of file Test_Polynomial.cpp.
TEST_F (PolynomialTest , helper_minus)
Definition at line 234 of file Test_Polynomial.cpp.
References Polynomial< FieldT >::minus().
TEST_F (PolynomialTest , add_operator)
Definition at line 247 of file Test_Polynomial.cpp.
References Polynomial< FieldT >::size().
TEST_F (PolynomialTest , add_operator_rvalue)
Definition at line 272 of file Test_Polynomial.cpp.
References Polynomial< FieldT >::size().
TEST_F (PolynomialTest , subtract_operator)
Definition at line 293 of file Test_Polynomial.cpp.
References Polynomial< FieldT >::size().
TEST_F (PolynomialTest , multiply_operator)
Definition at line 319 of file Test_Polynomial.cpp.
References Polynomial< FieldT >::size().