Polymetic: test/Test_Polynomial_gmpz.cpp File Reference
Test_Polynomial_gmpz.cpp File Reference
Contains the tests for the class Polynomial with field type as "mpz_class" which is the integer class from GMP.
#include "../include/Polynomial.hpp"
#include "../include/gmpsupport.hpp"
#include "gtest/gtest.h"
#include <stdexcept>
#include <utility>
Classes
class PolynomialMPZTest
Functions
TEST_F (PolynomialMPZTest, constructor_init_list)
TEST_F (PolynomialMPZTest, appendTerm)
TEST_F (PolynomialMPZTest, constructor_copy)
TEST_F (PolynomialMPZTest, constructor_move)
TEST_F (PolynomialMPZTest, assignment_move)
TEST_F (PolynomialMPZTest, access_operator_out_of_range_exception)
TEST_F (PolynomialMPZTest, friend_swap)
TEST_F (PolynomialMPZTest, helper_trim)
TEST_F (PolynomialMPZTest, sum_assign_operator)
TEST_F (PolynomialMPZTest, sum_assign_operator_rvalue_ref)
TEST_F (PolynomialMPZTest, subtract_assign_operator)
TEST_F (PolynomialMPZTest, subtract_assign_operator_rvalue_ref)
TEST_F (PolynomialMPZTest, unary_minus_operator_rvalue)
TEST_F (PolynomialMPZTest, unary_minus_operator)
TEST_F (PolynomialMPZTest, helper_minus)
TEST_F (PolynomialMPZTest, add_operator)
TEST_F (PolynomialMPZTest, add_operator_rvalue)
TEST_F (PolynomialMPZTest, subtract_operator)
TEST_F (PolynomialMPZTest, multiply_operator)
int main (int argc, char **argv)
Detailed Description
Contains the tests for the class Polynomial with field type as "mpz_class" which is the integer class from GMP.
Definition in file Test_Polynomial_gmpz.cpp.
Function Documentation
int main (int argc, char ** argv)
Definition at line 338 of file Test_Polynomial_gmpz.cpp.
TEST_F (PolynomialMPZTest , constructor_init_list)
Definition at line 48 of file Test_Polynomial_gmpz.cpp.
TEST_F (PolynomialMPZTest , appendTerm)
Definition at line 56 of file Test_Polynomial_gmpz.cpp.
References Polynomial< FieldT >::appendTerm().
TEST_F (PolynomialMPZTest , constructor_copy)
Definition at line 67 of file Test_Polynomial_gmpz.cpp.
TEST_F (PolynomialMPZTest , constructor_move)
Definition at line 76 of file Test_Polynomial_gmpz.cpp.
TEST_F (PolynomialMPZTest , assignment_move)
Definition at line 86 of file Test_Polynomial_gmpz.cpp.
TEST_F (PolynomialMPZTest , access_operator_out_of_range_exception)
Definition at line 97 of file Test_Polynomial_gmpz.cpp.
TEST_F (PolynomialMPZTest , friend_swap)
Definition at line 103 of file Test_Polynomial_gmpz.cpp.
TEST_F (PolynomialMPZTest , helper_trim)
Definition at line 118 of file Test_Polynomial_gmpz.cpp.
TEST_F (PolynomialMPZTest , sum_assign_operator)
Definition at line 134 of file Test_Polynomial_gmpz.cpp.
TEST_F (PolynomialMPZTest , sum_assign_operator_rvalue_ref)
Definition at line 155 of file Test_Polynomial_gmpz.cpp.
TEST_F (PolynomialMPZTest , subtract_assign_operator)
Definition at line 169 of file Test_Polynomial_gmpz.cpp.
TEST_F (PolynomialMPZTest , subtract_assign_operator_rvalue_ref)
Definition at line 190 of file Test_Polynomial_gmpz.cpp.
TEST_F (PolynomialMPZTest , unary_minus_operator_rvalue)
Definition at line 204 of file Test_Polynomial_gmpz.cpp.
TEST_F (PolynomialMPZTest , unary_minus_operator)
Definition at line 213 of file Test_Polynomial_gmpz.cpp.
TEST_F (PolynomialMPZTest , helper_minus)
Definition at line 223 of file Test_Polynomial_gmpz.cpp.
References Polynomial< FieldT >::minus().
TEST_F (PolynomialMPZTest , add_operator)
Definition at line 236 of file Test_Polynomial_gmpz.cpp.
References Polynomial< FieldT >::size().
TEST_F (PolynomialMPZTest , add_operator_rvalue)
Definition at line 261 of file Test_Polynomial_gmpz.cpp.
References Polynomial< FieldT >::size().
TEST_F (PolynomialMPZTest , subtract_operator)
Definition at line 282 of file Test_Polynomial_gmpz.cpp.
References Polynomial< FieldT >::size().
TEST_F (PolynomialMPZTest , multiply_operator)
Definition at line 308 of file Test_Polynomial_gmpz.cpp.
References Polynomial< FieldT >::size().